### ISSUE TITLE
Getting this error all of a sudden today. Worked fine for months before.

### ISSUE THREAD

**Issue by SkinnySkelly** [TheFrenchGhosty/TheFrenchGhostys-YouTube-DL-Archivist-Scripts#11]
ERROR: 'content_html'
Traceback (most recent call last):
  File "c:\python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 807, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "c:\python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 968, in process_ie_result
    ie_entries, playliststart, playlistend))
  File "c:\python37\lib\site-packages\youtube_dl\extractor\youtube.py", line 314, in _entries
    content_html = more['content_html']
KeyError: 'content_html'

Using windows 10. Tried the bat file and the ps1 file both produce the same result.

**Comment by po5** [comment]
This is fixed in the latest youtube-dl version, run `youtube-dl -U`.
Please file youtube-dl issues on the youtube-dl repo.
